# Preliminary or not- one can never be too early to secure opportunistic funding channels. Every dollar donated will bring me one step closer to actualizing my dreams into reality.
# SLUSH FUND: All contributions will be stricly to help pay for post-graduate's. It's the next logical step to get emmersed in what I enjoy most.
# Whether it's a cup of coffee, or a star on this repo, I'm just happy that I found my niche. Where fun meets hobby. Thank you for viewing!
# Let's make tomorrow better, together today.

github: qikevinl
thanks_dev: u/gh/qikevinl
patreon: qikevinl
buy_me_a_coffee: qikevinl
