"""
Neurotransmitter Systems
Generated by LearnViz

Visualizes dopamine, serotonin, and norepinephrine pathways.
"""
from manim import *
import numpy as np


class TextManager:
    def __init__(self, scene):
        self.scene = scene
        self.active_texts = {}
        self.regions = {"title": UP * 3.5, "top": UP * 3.0, "bottom": DOWN * 3.3, "center": ORIGIN}

    def show(self, text: str, region: str = "bottom", font_size: int = 22, color=WHITE, duration: float = 0.5):
        if region in self.active_texts:
            self.scene.play(FadeOut(self.active_texts[region]), run_time=0.2)
        text_obj = Text(text, font_size=font_size, color=color)
        text_obj.move_to(self.regions.get(region, ORIGIN))
        if text_obj.width > 13:
            text_obj.scale(13 / text_obj.width)
        self.scene.play(Write(text_obj), run_time=duration)
        self.active_texts[region] = text_obj
        return text_obj

    def clear(self, region: str = None):
        if region and region in self.active_texts:
            self.scene.play(FadeOut(self.active_texts[region]), run_time=0.2)
            del self.active_texts[region]
        elif region is None and self.active_texts:
            self.scene.play(*[FadeOut(t) for t in self.active_texts.values()], run_time=0.3)
            self.active_texts.clear()


class NeurotransmitterScene(Scene):
    def construct(self):
        self.tm = TextManager(self)

        self.show_intro()
        self.show_overview()
        self.show_dopamine()
        self.show_serotonin()
        self.show_norepinephrine()
        self.show_comparison()
        self.wait(2)

    def show_intro(self):
        title = Text("Neurotransmitter Systems", font_size=44)
        subtitle = Text("The brain's chemical messengers", font_size=24, color=GRAY)
        subtitle.next_to(title, DOWN, buff=0.3)

        self.play(Write(title))
        self.play(FadeIn(subtitle))
        self.wait(1)

        intro = Text(
            "Neurotransmitters are chemicals that transmit signals\n"
            "between neurons, controlling mood, movement, and cognition",
            font_size=18, color=BLUE_B
        )
        intro.next_to(subtitle, DOWN, buff=0.5)
        self.play(FadeIn(intro))
        self.wait(2)
        self.play(FadeOut(title), FadeOut(subtitle), FadeOut(intro))

    def show_overview(self):
        self.tm.show("Three major neurotransmitter systems regulate brain function", region="bottom")

        # Three colored boxes
        systems = VGroup()
        colors = [("#FF6B6B", "Dopamine\n(DA)", "Reward, Movement"),
                  ("#4ECDC4", "Serotonin\n(5-HT)", "Mood, Sleep"),
                  ("#FFE66D", "Norepinephrine\n(NE)", "Alertness, Stress")]

        for i, (color, name, function) in enumerate(colors):
            box = RoundedRectangle(width=3.5, height=2, corner_radius=0.2,
                                   fill_opacity=0.7, fill_color=color, stroke_color=WHITE)
            box.shift(LEFT * 4 + RIGHT * i * 4)

            title = Text(name, font_size=18, color=WHITE)
            title.move_to(box.get_center() + UP * 0.3)

            func = Text(function, font_size=14, color=WHITE)
            func.move_to(box.get_center() + DOWN * 0.4)

            systems.add(VGroup(box, title, func))

        self.play(Create(systems), run_time=2)
        self.wait(2)
        self.play(FadeOut(systems))

    def show_dopamine(self):
        self.tm.show("DOPAMINE: The reward and movement neurotransmitter", region="top", color="#FF6B6B")

        # Brain outline
        brain = Ellipse(width=6, height=5, color=PINK, fill_opacity=0.2)

        # VTA (source)
        vta = Dot(DOWN * 1.5, color="#FF6B6B", radius=0.3)
        vta_label = Text("VTA\n(Source)", font_size=12, color="#FF6B6B")
        vta_label.next_to(vta, DOWN, buff=0.1)

        # SNc
        snc = Dot(DOWN * 1.5 + LEFT * 1, color="#FF6B6B", radius=0.25)
        snc_label = Text("SNc", font_size=10, color="#FF6B6B")
        snc_label.next_to(snc, LEFT, buff=0.1)

        # Target regions
        pfc = Dot(UP * 1.5 + LEFT * 1, color=BLUE, radius=0.25)
        pfc_label = Text("PFC\n(Decision)", font_size=10, color=BLUE)
        pfc_label.next_to(pfc, UP, buff=0.1)

        nac = Dot(UP * 0.5, color=GREEN, radius=0.25)
        nac_label = Text("NAc\n(Reward)", font_size=10, color=GREEN)
        nac_label.next_to(nac, RIGHT, buff=0.1)

        striatum = Dot(UP * 0.5 + LEFT * 1.5, color=YELLOW, radius=0.25)
        striatum_label = Text("Striatum\n(Movement)", font_size=10, color=YELLOW)
        striatum_label.next_to(striatum, LEFT, buff=0.1)

        self.play(Create(brain))
        self.play(Create(vta), Write(vta_label), Create(snc), Write(snc_label))

        self.tm.show("Dopamine neurons in VTA and SNc project to multiple brain regions", region="bottom")

        # Pathways
        path1 = Arrow(vta.get_center(), pfc.get_center(), color="#FF6B6B", stroke_width=3, buff=0.3)
        path2 = Arrow(vta.get_center(), nac.get_center(), color="#FF6B6B", stroke_width=3, buff=0.3)
        path3 = Arrow(snc.get_center(), striatum.get_center(), color="#FF6B6B", stroke_width=3, buff=0.3)

        self.play(Create(pfc), Write(pfc_label), Create(path1))
        self.play(Create(nac), Write(nac_label), Create(path2))
        self.play(Create(striatum), Write(striatum_label), Create(path3))

        self.tm.show("Dopamine controls: reward seeking, motivation, and motor control", region="bottom", color="#FF6B6B")
        self.wait(2)

        self.play(FadeOut(*self.mobjects[:-1]))  # Keep TextManager text

    def show_serotonin(self):
        self.tm.show("SEROTONIN: The mood and well-being neurotransmitter", region="top", color="#4ECDC4")

        brain = Ellipse(width=6, height=5, color=PINK, fill_opacity=0.2)

        # Raphe nuclei (source)
        raphe = Dot(DOWN * 1.8, color="#4ECDC4", radius=0.3)
        raphe_label = Text("Raphe Nuclei\n(Source)", font_size=12, color="#4ECDC4")
        raphe_label.next_to(raphe, DOWN, buff=0.1)

        self.play(Create(brain))
        self.play(Create(raphe), Write(raphe_label))

        self.tm.show("Serotonin projects WIDELY throughout the entire brain", region="bottom")

        # Wide projections
        targets = [UP * 1.5, UP * 1.5 + LEFT * 1.5, UP * 1.5 + RIGHT * 1.5,
                   UP * 0.5 + LEFT * 2, UP * 0.5 + RIGHT * 2, ORIGIN + LEFT * 1.5]

        paths = VGroup()
        dots = VGroup()
        for t in targets:
            dot = Dot(t, color="#4ECDC4", radius=0.15)
            path = Arrow(raphe.get_center(), t, color="#4ECDC4", stroke_width=2, buff=0.2)
            paths.add(path)
            dots.add(dot)

        self.play(Create(paths), Create(dots), run_time=2)

        self.tm.show("Serotonin regulates: mood, sleep, appetite, and anxiety", region="bottom", color="#4ECDC4")
        self.wait(2)

        self.play(FadeOut(*self.mobjects[:-1]))

    def show_norepinephrine(self):
        self.tm.show("NOREPINEPHRINE: The alertness and stress neurotransmitter", region="top", color="#FFE66D")

        brain = Ellipse(width=6, height=5, color=PINK, fill_opacity=0.2)

        # Locus coeruleus (source)
        lc = Dot(DOWN * 1.2 + RIGHT * 0.5, color="#FFE66D", radius=0.3)
        lc_label = Text("Locus Coeruleus\n(Source)", font_size=12, color="#FFE66D")
        lc_label.next_to(lc, DOWN, buff=0.1)

        self.play(Create(brain))
        self.play(Create(lc), Write(lc_label))

        self.tm.show("The locus coeruleus is tiny but projects everywhere", region="bottom")

        # Widespread projections
        targets = [UP * 1.8, UP * 1.5 + LEFT * 2, UP * 1.5 + RIGHT * 2,
                   UP * 0.5 + LEFT * 2.5, UP * 0.5 + RIGHT * 2.5,
                   ORIGIN + LEFT * 2, DOWN * 0.5 + RIGHT * 2]

        paths = VGroup()
        for t in targets:
            path = Arrow(lc.get_center(), t, color="#FFE66D", stroke_width=2, buff=0.2)
            paths.add(path)

        self.play(Create(paths), run_time=2)

        # Stress response indicator
        alert = Text("!", font_size=36, color=RED)
        alert.move_to(UP * 2)
        self.play(FadeIn(alert, scale=2))

        self.tm.show("NE triggers fight-or-flight: increased heart rate, alertness, focus", region="bottom", color="#FFE66D")
        self.wait(2)

        self.play(FadeOut(*self.mobjects[:-1]))

    def show_comparison(self):
        self.tm.clear()

        # Comparison table
        title = Text("Neurotransmitter Comparison", font_size=28)
        title.to_edge(UP, buff=0.5)

        table_data = [
            ["System", "Source", "Function", "Disorders"],
            ["Dopamine", "VTA, SNc", "Reward, Movement", "Parkinson's, Addiction"],
            ["Serotonin", "Raphe", "Mood, Sleep", "Depression, Anxiety"],
            ["Norepinephrine", "LC", "Alertness", "PTSD, ADHD"],
        ]

        table = VGroup()
        colors = [WHITE, "#FF6B6B", "#4ECDC4", "#FFE66D"]

        for i, row in enumerate(table_data):
            row_group = VGroup()
            for j, cell in enumerate(row):
                text = Text(cell, font_size=14 if i == 0 else 12,
                           color=colors[i] if j == 0 else WHITE)
                text.move_to(LEFT * 4.5 + RIGHT * j * 3 + UP * 1 + DOWN * i * 0.8)
                row_group.add(text)
            table.add(row_group)

        self.play(Write(title))
        self.play(Write(table), run_time=2)

        final = Text("These systems interact and balance each other for healthy brain function", font_size=16, color=BLUE_B)
        final.to_edge(DOWN, buff=0.8)
        self.play(FadeIn(final))


if __name__ == "__main__":
    pass
