"""
How does DNS work
Generated by LearnViz

This is a template - fill in the scene implementations.
"""
from manim import *

class GeneratedScene(Scene):
    def construct(self):
        # Run all scenes
        self.scene_1_intro()
        self.scene_2_main()
        self.scene_3_outro()


    def scene_1_intro(self):
        """
        Introduce the concept: How does DNS work...
        Duration: 3.0s
        """
        # TODO: Implement intro
        text = Text("Introduce the concept: How does DNS work...", font_size=24)
        self.play(Write(text))
        self.wait(3.0)
        self.play(FadeOut(text))

    def scene_2_main(self):
        """
        Show the main concept visualization
        Duration: 5.0s
        """
        # TODO: Implement main
        text = Text("Show the main concept visualization...", font_size=24)
        self.play(Write(text))
        self.wait(5.0)
        self.play(FadeOut(text))

    def scene_3_outro(self):
        """
        Closing summary
        Duration: 2.0s
        """
        # TODO: Implement outro
        text = Text("Closing summary...", font_size=24)
        self.play(Write(text))
        self.wait(2.0)
        self.play(FadeOut(text))


if __name__ == "__main__":
    # Render with: manim -pql generated_scene.py GeneratedScene
    pass
