/**
 * Ethical Neurosecurity Code of Ethics — Single Source of Truth
 *
 * This file drives both:
 *   1. The security page rendering (src/pages/security.astro)
 *   2. The governance markdown doc (governance/ETHICAL-NEUROSECURITY-CODE-OF-ETHICS.md)
 *
 * To update the Code of Ethics, edit this file and run: npm run build
 * The governance markdown is generated by: scripts/generate-ethics-md.ts
 */

export const ETHICS_VERSION = '0.0.1';
export const ETHICS_STATUS = 'Draft';
export const ETHICS_DATE = 'February 2026';
export const ETHICS_AUTHOR = 'Kevin L. Qi';
export const ETHICS_LICENSE = 'CC-BY 4.0';
export const ETHICS_LICENSE_URL = 'https://creativecommons.org/licenses/by/4.0/';

export interface Canon {
  number: string;
  title: string;
  description: string;
  sources: string;
  color: string;
}

export interface Principle {
  number: number;
  title: string;
  description: string;
  sources: string;
}

export interface CrossRef {
  principle: string;
  cehIsc2: string;
  bioethics: string;
  neurorights: string;
  digitalIntlLaw: string;
}

export const INTENT = 'This document exists to protect normal people. Neurosecurity research is new, the tools are powerful, and the consequences of mistakes are not like crashing a server. Someone exploring BCI security for the first time could accidentally probe the wrong system, collect neural data they should not have, or publish a technique without realizing the dual-use implications. This code sets guidelines and guardrails to the best of our current understanding so that well-meaning researchers do not cause harm by accident. It is not a legal document. It is a starting point, written by one person, that needs many more people helping to get it right.';

export const PREAMBLE = [
  'Neurotechnology is advancing faster than the rules protecting the people who use it. Brain-computer interfaces are entering clinical trials, consumer EEG devices are shipping to millions, and silent speech decoding is accurate enough to worry about. The security community that protects these systems needs its own ethical foundation.',
  'Ethical hackers protect servers, networks, and applications. Ethical neurosecurity researchers protect brains. The principles are the same: get authorization before you test, report what you find, do not cause harm, protect what you access. But the consequences are different. A compromised server can be reimaged. A compromised brain may not recover. That difference demands a code of ethics written specifically for this work.',
  'This code is open. It builds on decades of work in cybersecurity ethics, bioethics, neurorights, and human rights law. Anyone working in neurosecurity, whether in research, clinical settings, industry, or government, is invited to adopt, critique, and improve it.',
];

export const CANONS: Canon[] = [
  {
    number: 'I',
    title: 'Protect cognitive sovereignty',
    description: "Protect the individual's right to mental privacy, psychological continuity, and freedom of thought. Neural data belongs to the person it came from. Not the device manufacturer. Not the researcher. Not the state.",
    sources: "Chile Neurorights Law, Yuste's 5 Neurorights, Ienca & Andorno (Right to Cognitive Liberty), OECD Principle 9, UNESCO UDBHR Art. 5",
    color: '#3b82f6',
  },
  {
    number: 'II',
    title: 'Act with integrity and transparency',
    description: 'Be honest about your methods, your findings, and your limitations. Disclose conflicts of interest. Disclose dual-use potential of any technique you publish. Never misrepresent your qualifications or the scope of your testing.',
    sources: '(ISC)² Canon 2, CEH Clauses 7/10, CREST Code of Ethics (Integrity/Objectivity), Belmont Report (Respect for Persons), Helsinki Art. 23',
    color: '#10b981',
  },
  {
    number: 'III',
    title: 'Provide competent and careful service',
    description: 'Only perform neurosecurity work within your competence. Neural systems are not servers. Understand the biology before you test the security. When you are out of your depth, say so and bring in the right expertise.',
    sources: '(ISC)² Canon 3, CEH Clause 3, Nuremberg Code Point 8, CREST (Competence), PTES Pre-Engagement',
    color: '#f59e0b',
  },
  {
    number: 'IV',
    title: 'Advance and protect the field',
    description: 'Contribute to the neurosecurity community through responsible research, open collaboration, and knowledge sharing. Mentor newcomers. Hold each other accountable. The field is too young and too important to get wrong.',
    sources: '(ISC)² Canon 4, CEH Clause 9, OECD Principles 4/5, Asilomar Principles 3/4, IEEE Neuroethics (Agency & Identity)',
    color: '#8b5cf6',
  },
];

export const PRINCIPLES: Principle[] = [
  {
    number: 1,
    title: 'Obtain informed neural consent before any testing',
    description: 'Never access, probe, or test a neural interface without explicit written authorization from the device user and the system owner. For BCIs, the device user IS the person whose brain is connected. Informed consent must include what neural data will be collected, how it will be used, and when it will be deleted. The person must understand what you might learn about their cognitive state in the process.',
    sources: 'CEH Clause 14 (authorized testing) + Nuremberg Code Point 1 (voluntary consent) + Belmont Report (informed consent) + Helsinki Art. 25-32 + Colorado HB24-1058 (affirmative opt-in) + California SB 1223 + OECD Principle 7',
  },
  {
    number: 2,
    title: 'Do no neural harm',
    description: 'Never perform any test that risks irreversible damage to neural tissue or cognitive function. A penetration test on a server can be rolled back. A penetration test that causes seizures, memory loss, or personality changes cannot. If there is any doubt about whether a technique could cause lasting harm, do not use it. This is the irreversibility threshold, and there is no equivalent in traditional security.',
    sources: 'CEH Clause 13 (don\'t compromise systems) + Nuremberg Code Points 4-5 (avoid suffering, no a priori reason for harm) + Belmont Report (beneficence) + Helsinki Art. 16-18 + Ienca & Andorno (Right to Mental Integrity) + OECD Principle 2 (safety)',
  },
  {
    number: 3,
    title: 'Protect neural data as the most sensitive category of personal information',
    description: 'Neural data can reveal thoughts, emotions, intentions, psychiatric conditions, and cognitive patterns that the person may not even be aware of themselves. Treat it with more care than you would treat medical records, biometric data, or financial information. Encrypt it in transit and at rest. Minimize what you collect. Delete it when the engagement ends. Never share it without explicit consent. A Neurorights Foundation audit (https://perseus-strategies.com/wp-content/uploads/2024/04/FINAL_Consumer_Neurotechnology_Report_Neurorights_Foundation_April-1.pdf) in 2024 found that 96.7% of consumer neurotech companies reserve the right to transfer brain data to third parties. Do not be one of them.',
    sources: 'CEH Clause 1 (confidentiality) + GDPR Article 9 (special categories) + Colorado HB24-1058 + California SB 1223 + Chile Neurorights (neurodata as organ) + OECD Principle 7 + CoE Convention 108+ (neural data as special category) + Helsinki Art. 24',
  },
  {
    number: 4,
    title: 'Never engage in or support malicious neural activities',
    description: 'Do not develop, distribute, or use tools designed to attack neural interfaces without authorization. Do not collaborate with actors seeking to weaponize neurotechnology for surveillance, coercion, or cognitive manipulation. Do not build neuroweapons. Do not assist in the extraction of thoughts, emotions, or memories without consent. Mexico\'s GLNN bill (introduced 2024, published in The Lancet Psychiatry: https://www.thelancet.com/journals/lanpsy/article/PIIS2215-0366(24)00286-4/abstract) proposes criminal penalties of 3-12 years for mental manipulation and unauthorized probing of neuronal activity. The severity is appropriate.',
    sources: 'CEH Clause 12 (no malicious hackers) + Budapest Convention Art. 2-6 (illegal access, interception, data interference) + Mexico GLNN (criminal penalties) + EU AI Act Art. 5(1)(a) (subliminal manipulation prohibition) + IEEE Neuroethics (Authority/Power)',
  },
  {
    number: 5,
    title: 'Maintain a neural safety cutoff at all times',
    description: "Any neurosecurity test involving active neural interfaces must have an immediate stop mechanism. If the subject reports discomfort, cognitive changes, or unusual sensations, halt all testing immediately. The subject's right to terminate participation is absolute and cannot be overridden by research goals, contractual obligations, or project timelines. This applies during testing and for a monitoring period after.",
    sources: "Nuremberg Code Point 9 (subject's right to terminate) + Point 10 (scientist's duty to terminate) + Helsinki Art. 18 (stop when risks outweigh benefits) + PTES Rules of Engagement (emergency stop) + EU Trustworthy AI Requirement 1 (human oversight)",
  },
  {
    number: 6,
    title: 'Handle involuntary cognitive disclosures with care',
    description: "During neurosecurity work, you may inadvertently learn things about a person's cognitive state, emotional patterns, psychiatric conditions, or inner thoughts that they did not consent to reveal. This is different from finding a password in a pentest. If you discover cognitive or health information incidentally, treat it as privileged. Do not record it. Do not report it unless the person gives explicit consent or there is an immediate safety risk. The person's right to mental privacy does not disappear because you found a vulnerability.",
    sources: 'Yuste Neurorights (mental privacy) + Ienca & Andorno (Right to Mental Privacy) + Chile Neurorights + GDPR Art. 9 (health data) + Helsinki Art. 24 (privacy/confidentiality) + Montreal Declaration Principle 3 (privacy and intimacy)',
  },
  {
    number: 7,
    title: 'Report all vulnerabilities through responsible disclosure',
    description: 'Report every neural security vulnerability you discover to the device manufacturer or responsible party through coordinated disclosure. Give them reasonable time to patch before any public disclosure. When you do publish, always include defensive countermeasures alongside the attack vector. Never publish a neural exploit without a corresponding defense. The dual-use potential of every technique in the TARA registry is exactly why this matters.',
    sources: 'CEH Clause 2 (disclose dangers) + CREST Code of Conduct (responsible disclosure) + OECD Principle 9 (anticipate misuse) + Asilomar Principle 5 (race avoidance) + PTES Phase 7 (reporting)',
  },
  {
    number: 8,
    title: 'Advocate for equitable access and protection from bias',
    description: 'Neurosecurity protections should not be a luxury. If a neural interface is secure for one population but vulnerable for another due to algorithmic bias, training data gaps, or economic barriers, that is a security failure. Work to ensure that the people who need neural interfaces the most, typically patients with severe disabilities, are not the ones left with the weakest protections. Test across diverse populations. Flag biased models. Push for open security standards that anyone can audit.',
    sources: 'Yuste Neurorights (equal access + protection from bias) + Belmont Report (justice) + Helsinki Art. 13 + UNESCO UDBHR Art. 10-11 + OECD Principle 3 (inclusivity) + Chile Neurorights + EU Trustworthy AI Requirement 5',
  },
  {
    number: 9,
    title: 'Stay within scope, stay within the law',
    description: 'All neurosecurity testing must operate within clearly defined scope boundaries documented in writing before work begins. Define exactly which devices, interfaces, and neural data streams are in-scope. Everything else is off-limits. Comply with all applicable laws, including neural data privacy statutes (Colorado HB24-1058, California SB 1223, the MIND Act when enacted), medical device regulations, and international cybercrime law (Budapest Convention). Unauthorized access to a neural interface is not a grey area. It is a crime against a person\'s brain.',
    sources: 'CEH Clauses 14/19 (authorized testing, legal compliance) + PTES Pre-Engagement (scope/rules of engagement) + Budapest Convention Art. 2-5 + Tallinn Manual Rules 1-4 (sovereignty) + Colorado/California neural data laws + Mexico GLNN',
  },
  {
    number: 10,
    title: 'Preserve personal identity and psychological continuity',
    description: "Never perform any action that alters a person's sense of self, personality, memories, or cognitive patterns without their explicit, informed consent. This includes neuromodulation, stimulation parameter changes, or any technique that could affect psychological continuity. The right to personal identity means that who you are before a neurosecurity assessment is who you should be after it. If a vulnerability you discover could be exploited to alter someone's identity, report it with the highest severity.",
    sources: 'Ienca & Andorno (Right to Psychological Continuity) + Yuste Neurorights (personal identity) + Chile Neurorights + IEEE Neuroethics (Agency & Identity) + CoE DH-BIO (mental integrity) + UNESCO UDBHR Art. 3 (human dignity)',
  },
  {
    number: 11,
    title: 'Maintain competence across both security and neuroscience',
    description: 'Neurosecurity sits at the intersection of cybersecurity, neuroscience, bioethics, and clinical medicine. Stay current in all of them. Understand the biology of what you are testing. Know the difference between cortical oscillation bands. Understand how neural signals propagate. Know what a seizure looks like. If you only know the security side, partner with someone who knows the neuroscience. If you only know the neuroscience, partner with someone who knows the security. Neither half is optional.',
    sources: 'CEH Clauses 3/9/25 (competence, continuous learning) + (ISC)² Canon 3 + CREST (Competence) + OECD Principle 4 (scientific collaboration) + Nuremberg Code Point 8 (qualified persons)',
  },
  {
    number: 12,
    title: 'Accept accountability for your work',
    description: 'You are responsible for the consequences of your neurosecurity work. Document everything. Maintain audit trails. If something goes wrong during testing, report it immediately. If your published research is used to cause harm, engage with the response. Accountability is not optional in a field where the target is a human brain. The (ISC)² requires members to report ethics breaches by other members. We adopt the same standard here. If you see someone violating this code, say something.',
    sources: '(ISC)² (obligation to report violations) + EU Trustworthy AI Requirement 7 (accountability) + UNESCO AI Principle 8 + Asilomar Principle 9 (responsibility) + Helsinki Art. 23 (ethics committee oversight) + NIST CSF Govern function',
  },
];

export const CROSS_REFERENCES: CrossRef[] = [
  { principle: '1. Neural Consent', cehIsc2: 'CEH #14', bioethics: 'Nuremberg 1, Belmont, Helsinki 25-32', neurorights: 'Chile, Colorado, California, OECD 7', digitalIntlLaw: 'GDPR Art. 9, PTES' },
  { principle: '2. No Neural Harm', cehIsc2: 'CEH #13', bioethics: 'Nuremberg 4-5, Belmont, Helsinki 16-18', neurorights: 'Ienca (Mental Integrity), OECD 2', digitalIntlLaw: 'EU AI Act Art. 5' },
  { principle: '3. Data Protection', cehIsc2: 'CEH #1', bioethics: 'Helsinki 24', neurorights: 'Chile (neurodata = organ), OECD 7', digitalIntlLaw: 'GDPR Art. 9, CoE 108+' },
  { principle: '4. No Malicious Activity', cehIsc2: 'CEH #12', bioethics: 'Nuremberg 4', neurorights: 'Mexico GLNN, IEEE (Authority)', digitalIntlLaw: 'Budapest Conv. Art. 2-6' },
  { principle: '5. Safety Cutoff', cehIsc2: '\u2014', bioethics: 'Nuremberg 9-10, Helsinki 18', neurorights: '\u2014', digitalIntlLaw: 'PTES ROE, EU Trust. AI 1' },
  { principle: '6. Cognitive Disclosure', cehIsc2: 'CEH #1', bioethics: 'Helsinki 24', neurorights: 'Yuste (mental privacy), Ienca', digitalIntlLaw: 'Montreal Decl. 3' },
  { principle: '7. Responsible Disclosure', cehIsc2: 'CEH #2', bioethics: '\u2014', neurorights: 'OECD 9 (anticipate misuse)', digitalIntlLaw: 'CREST, Asilomar 5' },
  { principle: '8. Equitable Access', cehIsc2: '\u2014', bioethics: 'Belmont (justice), Helsinki 13', neurorights: 'Yuste (equal access, bias), Chile, OECD 3', digitalIntlLaw: 'EU Trust. AI 5, UNESCO 10-11' },
  { principle: '9. Scope & Legal', cehIsc2: 'CEH #14, #19', bioethics: '\u2014', neurorights: 'Colorado, California, Mexico GLNN', digitalIntlLaw: 'Budapest Conv., Tallinn, PTES' },
  { principle: '10. Identity Preservation', cehIsc2: '\u2014', bioethics: 'UNESCO UDBHR Art. 3', neurorights: 'Ienca (Psych. Continuity), Yuste, Chile', digitalIntlLaw: 'IEEE (Agency/Identity)' },
  { principle: '11. Cross-Domain Competence', cehIsc2: 'CEH #3, #9, #25', bioethics: 'Nuremberg 8', neurorights: 'OECD 4', digitalIntlLaw: 'CREST (Competence)' },
  { principle: '12. Accountability', cehIsc2: '(ISC)² (report)', bioethics: 'Helsinki 23', neurorights: 'UNESCO AI 8', digitalIntlLaw: 'EU Trust. AI 7, NIST Govern, Asilomar 9' },
];

export const INTRO_TEXT = 'This code adapts the structure and principles of the EC-Council Certified Ethical Hacker (CEH) Code of Ethics and the (ISC)² Code of Ethics for the neurosecurity domain. Ethical hacking already solved many governance problems for traditional systems. We are taking those lessons and applying them where the stakes are highest: the human brain.';

export const FRAMEWORKS_TEXT = 'Each principle below is cross-referenced to the international frameworks that inform it: the OECD Recommendation on Neurotechnology (2019), UNESCO Recommendation on the Ethics of AI (2021), the Belmont Report (1979), the Declaration of Helsinki, the Chilean Neurorights Law (2021), GDPR Article 9, the IEEE Neuroethics Framework, Budapest Convention on Cybercrime, and the five neurorights proposed by Yuste et al. and Ienca & Andorno.';

/** Links used in the intro paragraphs on the web page */
export const FRAMEWORK_LINKS = {
  ceh: 'https://cert.eccouncil.org/code-of-ethics.html',
  isc2: 'https://www.isc2.org/ethics',
  oecd: 'https://www.oecd.org/science/recommendation-on-responsible-innovation-in-neurotechnology.htm',
  unescoAi: 'https://www.unesco.org/en/artificial-intelligence/recommendation-ethics',
  belmont: 'https://www.hhs.gov/ohrp/regulations-and-policy/belmont-report/read-the-belmont-report/index.html',
  helsinki: 'https://www.wma.net/policies-post/wma-declaration-of-helsinki/',
  chileNeurorights: 'https://courier.unesco.org/en/articles/chile-pioneering-protection-neurorights',
  gdpr9: 'https://gdpr-info.eu/art-9-gdpr/',
  ieeeNeuroethics: 'https://brain.ieee.org/publications/ieee-neuroethics-framework/',
  budapest: 'https://rm.coe.int/1680081561',
  yuste: 'https://www.frontiersin.org/journals/human-neuroscience/articles/10.3389/fnhum.2021.701258/full',
  ienca: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC11542783/',
  neurorightsAudit: 'https://perseus-strategies.com/wp-content/uploads/2024/04/FINAL_Consumer_Neurotechnology_Report_Neurorights_Foundation_April-1.pdf',
  lancetGlnn: 'https://www.thelancet.com/journals/lanpsy/article/PIIS2215-0366(24)00286-4/abstract',
};
